[package]
name = "DexonicAssetVault"
version = "1.0.0"
authors = ["Your Name <your.email@example.com>"]
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }

[addresses]
vault = "0xb380dc1036ffeed2f2fe06977a17275e4a71d9ca3a3df58b370aa7faba336c4d"
std = "0x1"
aptos_framework = "0x1" 